// <auto-generated />
using System;
using ClyvoVet.API.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace ClyvoVet.API.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20260908235000_AdaptarModeloClinico")]
    partial class AdaptarModeloClinico
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClyvoVet.API.Domain.Entities.Consulta", b =>
            {
                b.Property<int>("IdConsulta").HasColumnType("NUMBER(10)").HasColumnName("ID_CONSULTA");
                b.Property<DateTime>("DataConsulta").HasColumnType("DATE").HasColumnName("DATA_CONSULTA");
                b.Property<int>("IdPet").HasColumnType("NUMBER(10)").HasColumnName("ID_PET");
                b.Property<string>("Observacoes").HasMaxLength(300).HasColumnType("VARCHAR2(300)").HasColumnName("OBSERVACOES");
                b.Property<string>("Veterinario").HasMaxLength(100).HasColumnType("VARCHAR2(100)").HasColumnName("VETERINARIO");
                b.HasKey("IdConsulta");
                b.HasIndex("IdPet");
                b.ToTable("CONSULTA");
            });

            modelBuilder.Entity("ClyvoVet.API.Domain.Entities.Medicacao", b =>
            {
                b.Property<int>("IdMedicacao").HasColumnType("NUMBER(10)").HasColumnName("ID_MEDICACAO");
                b.Property<DateTime?>("DataFim").HasColumnType("DATE").HasColumnName("DATA_FIM");
                b.Property<DateTime?>("DataInicio").HasColumnType("DATE").HasColumnName("DATA_INICIO");
                b.Property<string>("Dose").HasMaxLength(50).HasColumnType("VARCHAR2(50)").HasColumnName("DOSE");
                b.Property<string>("Frequencia").HasMaxLength(50).HasColumnType("VARCHAR2(50)").HasColumnName("FREQUENCIA");
                b.Property<int>("IdPet").HasColumnType("NUMBER(10)").HasColumnName("ID_PET");
                b.Property<string>("Nome").IsRequired().HasMaxLength(100).HasColumnType("VARCHAR2(100)").HasColumnName("NOME");
                b.HasKey("IdMedicacao");
                b.HasIndex("IdPet");
                b.ToTable("MEDICACAO");
            });

            modelBuilder.Entity("ClyvoVet.API.Domain.Entities.Pet", b =>
            {
                b.Property<int>("IdPet").HasColumnType("NUMBER(10)").HasColumnName("ID_PET");
                b.Property<DateTime?>("DataNascimento").HasColumnType("DATE").HasColumnName("DATA_NASC");
                b.Property<string>("Especie").IsRequired().HasMaxLength(50).HasColumnType("VARCHAR2(50)").HasColumnName("ESPECIE");
                b.Property<int>("IdTutor").HasColumnType("NUMBER(10)").HasColumnName("ID_TUTOR");
                b.Property<string>("Nome").IsRequired().HasMaxLength(100).HasColumnType("VARCHAR2(100)").HasColumnName("NOME");
                b.Property<decimal?>("PesoKg").HasPrecision(5, 2).HasColumnType("NUMBER(5,2)").HasColumnName("PESO_KG");
                b.Property<string>("Raca").HasMaxLength(50).HasColumnType("VARCHAR2(50)").HasColumnName("RACA");
                b.HasKey("IdPet");
                b.HasIndex("IdTutor");
                b.ToTable("PET");
            });

            modelBuilder.Entity("ClyvoVet.API.Domain.Entities.Tutor", b =>
            {
                b.Property<int>("IdTutor").HasColumnType("NUMBER(10)").HasColumnName("ID_TUTOR");
                b.Property<string>("Cpf").IsRequired().HasMaxLength(14).HasColumnType("VARCHAR2(14)").HasColumnName("CPF");
                b.Property<string>("Email").IsRequired().HasMaxLength(100).HasColumnType("VARCHAR2(100)").HasColumnName("EMAIL");
                b.Property<string>("Nome").IsRequired().HasMaxLength(100).HasColumnType("VARCHAR2(100)").HasColumnName("NOME");
                b.Property<string>("Telefone").HasMaxLength(20).HasColumnType("VARCHAR2(20)").HasColumnName("TELEFONE");
                b.HasKey("IdTutor");
                b.ToTable("TUTOR");
            });

            modelBuilder.Entity("ClyvoVet.API.Domain.Entities.User", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("RAW(16)");
                b.Property<string>("Address").IsRequired().HasMaxLength(200).HasColumnType("NVARCHAR2(200)");
                b.Property<string>("Email").IsRequired().HasColumnType("NVARCHAR2(2000)");
                b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType("NVARCHAR2(100)");
                b.Property<string>("Password").IsRequired().HasColumnType("NVARCHAR2(2000)");
                b.Property<string>("Phone").IsRequired().HasMaxLength(20).HasColumnType("NVARCHAR2(20)");
                b.HasKey("Id");
                b.ToTable("Users");
            });

            modelBuilder.Entity("ClyvoVet.API.Domain.Entities.Consulta", b =>
            {
                b.HasOne("ClyvoVet.API.Domain.Entities.Pet", "Pet")
                    .WithMany("Consultas")
                    .HasForeignKey("IdPet")
                    .OnDelete(DeleteBehavior.NoAction)
                    .IsRequired()
                    .HasConstraintName("FK_CONSULTA_PET");
                b.Navigation("Pet");
            });

            modelBuilder.Entity("ClyvoVet.API.Domain.Entities.Medicacao", b =>
            {
                b.HasOne("ClyvoVet.API.Domain.Entities.Pet", "Pet")
                    .WithMany("Medicacoes")
                    .HasForeignKey("IdPet")
                    .OnDelete(DeleteBehavior.NoAction)
                    .IsRequired()
                    .HasConstraintName("FK_MEDICACAO_PET");
                b.Navigation("Pet");
            });

            modelBuilder.Entity("ClyvoVet.API.Domain.Entities.Pet", b =>
            {
                b.HasOne("ClyvoVet.API.Domain.Entities.Tutor", "Tutor")
                    .WithMany("Pets")
                    .HasForeignKey("IdTutor")
                    .OnDelete(DeleteBehavior.NoAction)
                    .IsRequired()
                    .HasConstraintName("FK_PET_TUTOR");
                b.Navigation("Tutor");
            });

            modelBuilder.Entity("ClyvoVet.API.Domain.Entities.Pet", b =>
            {
                b.Navigation("Consultas");
                b.Navigation("Medicacoes");
            });

            modelBuilder.Entity("ClyvoVet.API.Domain.Entities.Tutor", b => b.Navigation("Pets"));
#pragma warning restore 612, 618
        }
    }
}
